.PHONY: clean All

All:
	@echo "----------Building project:[ bfs - Debug ]----------"
	@cd "bfs" && "$(MAKE)" -f  "bfs.mk"
clean:
	@echo "----------Cleaning project:[ bfs - Debug ]----------"
	@cd "bfs" && "$(MAKE)" -f  "bfs.mk" clean
